# -*- coding: utf-8 -*-
"""Access OSCAR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTQG_T9TwMwaDt_RxWbpESPRgrhRjCbn

[Website here explains how to create access token](https://medium.com/@isabel.klint/gain-access-to-the-oscar-dataset-through-huggingface-f6eb0a7e4e27). Access token is needed for notebook login
"""

# !pip install datasets --quiet
# !pip install zstandard --quiet

from datasets import load_dataset, Dataset

# useful if you don’t have enough space on your disk to download the dataset, or
# if you don’t want to wait for your dataset to be downloaded before using it
dataset = load_dataset("oscar-corpus/OSCAR-2201",
                       use_auth_token=True,
                       language="fr",
                       #trust_remote_code=True,
                       streaming=True,
                       split="train"
                      )
print("loaded dataset...")

items_list = []
counter = 0
for item in dataset:
  #items_list.append(item)
  # if counter == 10:
  #   break
  # counter += 1
  if counter % 10000 == 0:
    print(counter)
  counter += 1

print("created list...")

print("List length:", len(items_list))



#all code in the next two cells from https://huggingface.co/docs/datasets/create_dataset

# def gen():
#   for item in items_list:
#     yield item

# new_dataset = Dataset.from_generator(gen)

# print(new_dataset)



